language: ruby
script: "bundle exec rake test"
cache: bundler
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
notifications:
  email:
    on_success: always
    on_failure: always
